spring.application.name=AiResumeOptimizer

spring.ai.google.genai.api-key=AIzaSyDqQwtU_i1auJWfjc7TcyInnquxh94ZhLE
#spring.ai.google.genai.project-id=gen-lang-client-0846196115
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

#DB config

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/launchpadDB
spring.datasource.username=postgres
spring.datasource.password=123

#hibernate config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
